# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    filter_sets:
        thumb:
            format: jpeg
            quality: 80
            filters:
                thumbnail: { size: [360, 230], mode: outbond }
        #my_thumb_webp:
            #format: webp
            #quality: 100
            #filters:
                #thumbnail: { size: [223, 223], mode: inset }
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
