#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# index:
#     path: /
#     controller: App\Controller\AccueilController::bonjour

# newIntervenant_success:
#     path: /newintersuccess
#     controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
#     defaults:
#         template: "intervenant/static/success.html.twig"
